language: node_js
sudo: false
matrix:
  include:
    - node_js: "0.10"
    - node_js: "0.12"
    - node_js: "4"
    - node_js: "5"
  fast_finish: true
script: "jshint index.js && jasmine-node --captureExceptions spec && promises-aplus-tests index.js"
branches:
  only:
    - master

